### PR TITLE
Sensor block

### PR DESCRIPTION
**Pull request by alanb128**
### Hey there, appreciated contributor!

Have you taken a look at the [contribution guidelines](../CONTRIBUTING.md) for this project? To enable our CI to work correctly and version the releases of the project, you need to ensure your commit messages contain the required information [detailed here](../CONTRIBUTING.md). Thank you!

### CODE REVIEW

**Comment by tmigone** [comment]
@balena-ci retest

**Comment by tmigone** [comment]
@balena-ci retest

**Comment by tmigone** [comment]
@balena-ci retest

**Comment by tmigone** [comment]
@balena-ci I self-certify!

**Review by phil-d-wilson — APPROVED** [review]
lgtm

**Comment by phil-d-wilson** [comment]
@balena-ci retest

**Review by phil-d-wilson — APPROVED** [review]

**Comment by phil-d-wilson** [comment]
@balena-ci retest

**Pull request closed without merging**
